services:
  - type: web
    name: tregu-api
    env: python
    plan: standard
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      echo "BUILD OK"
    startCommand: |
      cd backend
      bash ./start.sh
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: PUBLIC_CDN_BASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALG
        value: HS256
      - key: CORS_ORIGINS
        value: https://www.tregu.com,https://tregu.onrender.com
      - key: RATE_LIMIT_GLOBAL
        value: 200/min
      - key: AI_LOG_RETENTION_DAYS
        value: 30

  - type: static_site
    name: tregu-frontend
    env: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build
      npm run export || echo "If using SSR, deploy as a Node web service instead."
    staticPublishPath: frontend/out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        sync: false
      - key: NEXT_PUBLIC_CDN_BASE
        sync: false

  - type: worker
    name: tregu-worker
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m app.worker
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
