services:
  - type: web
    name: tregu-api
    runtime: python
    buildCommand: cd tregu_backend && pip install -r requirements.txt
    startCommand: cd tregu_backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: PUBLIC_CDN_BASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALG
        value: HS256
      - key: CORS_ORIGINS
        value: https://www.tregu.com,https://tregu.onrender.com
      - key: RATE_LIMIT_GLOBAL
        value: 200/min

  - type: web
    name: tregu-frontend
    runtime: static
    buildCommand: cd tregu_frontend && npm ci && npm run build && npm run export
    staticPublishPath: tregu_frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        sync: false

