// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/(auth)/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(marketing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/(marketing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/2fa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/2fa">> = Specific
  const handler = {} as typeof import("../../app/account/2fa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/settings">> = Specific
  const handler = {} as typeof import("../../app/account/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/deletions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/deletions">> = Specific
  const handler = {} as typeof import("../../app/admin/deletions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-test">> = Specific
  const handler = {} as typeof import("../../app/ai-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai">> = Specific
  const handler = {} as typeof import("../../app/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/dev-force/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/dev-force">> = Specific
  const handler = {} as typeof import("../../app/auth/dev-force/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/status">> = Specific
  const handler = {} as typeof import("../../app/auth/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/business/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/business/catalog">> = Specific
  const handler = {} as typeof import("../../app/business/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/business/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/business/new">> = Specific
  const handler = {} as typeof import("../../app/business/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/business">> = Specific
  const handler = {} as typeof import("../../app/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catalog/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/upload">> = Specific
  const handler = {} as typeof import("../../app/catalog/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/copilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copilot">> = Specific
  const handler = {} as typeof import("../../app/copilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/access">> = Specific
  const handler = {} as typeof import("../../app/dashboard/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/appearance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/barcode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/barcode">> = Specific
  const handler = {} as typeof import("../../app/dashboard/barcode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/buyer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/buyer">> = Specific
  const handler = {} as typeof import("../../app/dashboard/buyer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/catalog">> = Specific
  const handler = {} as typeof import("../../app/dashboard/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/create">> = Specific
  const handler = {} as typeof import("../../app/dashboard/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/locations">> = Specific
  const handler = {} as typeof import("../../app/dashboard/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/seller/Inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/seller/Inventory">> = Specific
  const handler = {} as typeof import("../../app/dashboard/seller/Inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems/ai">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/oms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems/oms">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/oms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/scm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems/scm">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/scm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/tms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems/tms">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/tms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/systems/wms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/systems/wms">> = Specific
  const handler = {} as typeof import("../../app/dashboard/systems/wms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/[system]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/[system]">> = Specific
  const handler = {} as typeof import("../../app/enterprise/[system]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/admin/navigation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/admin/navigation">> = Specific
  const handler = {} as typeof import("../../app/enterprise/admin/navigation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/ai/console/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/ai/console">> = Specific
  const handler = {} as typeof import("../../app/enterprise/ai/console/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/analytics/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/analytics/dashboard">> = Specific
  const handler = {} as typeof import("../../app/enterprise/analytics/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/analytics/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/analytics/library">> = Specific
  const handler = {} as typeof import("../../app/enterprise/analytics/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/analytics/targets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/analytics/targets">> = Specific
  const handler = {} as typeof import("../../app/enterprise/analytics/targets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/analytics/theme-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/analytics/theme-settings">> = Specific
  const handler = {} as typeof import("../../app/enterprise/analytics/theme-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/dashboard">> = Specific
  const handler = {} as typeof import("../../app/enterprise/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/integration/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/integration/audit">> = Specific
  const handler = {} as typeof import("../../app/enterprise/integration/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/integration/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/integration/customers">> = Specific
  const handler = {} as typeof import("../../app/enterprise/integration/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/integration/map-fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/integration/map-fields">> = Specific
  const handler = {} as typeof import("../../app/enterprise/integration/map-fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/integration/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/integration/orders">> = Specific
  const handler = {} as typeof import("../../app/enterprise/integration/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/inventory">> = Specific
  const handler = {} as typeof import("../../app/enterprise/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/market/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/market/history">> = Specific
  const handler = {} as typeof import("../../app/enterprise/market/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/market">> = Specific
  const handler = {} as typeof import("../../app/enterprise/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/market/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/market/upload">> = Specific
  const handler = {} as typeof import("../../app/enterprise/market/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise">> = Specific
  const handler = {} as typeof import("../../app/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/settings/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/settings/policies">> = Specific
  const handler = {} as typeof import("../../app/enterprise/settings/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/export">> = Specific
  const handler = {} as typeof import("../../app/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../app/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacy">> = Specific
  const handler = {} as typeof import("../../app/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/terms">> = Specific
  const handler = {} as typeof import("../../app/legal/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logout">> = Specific
  const handler = {} as typeof import("../../app/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market/[postId]">> = Specific
  const handler = {} as typeof import("../../app/market/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market/feed">> = Specific
  const handler = {} as typeof import("../../app/market/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market">> = Specific
  const handler = {} as typeof import("../../app/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../app/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboard">> = Specific
  const handler = {} as typeof import("../../app/onboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboard/profile">> = Specific
  const handler = {} as typeof import("../../app/onboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pods">> = Specific
  const handler = {} as typeof import("../../app/pods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/posts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/posts/new">> = Specific
  const handler = {} as typeof import("../../app/posts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller[id]">> = Specific
  const handler = {} as typeof import("../../app/seller[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/access">> = Specific
  const handler = {} as typeof import("../../app/settings/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account">> = Specific
  const handler = {} as typeof import("../../app/settings/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/appearance">> = Specific
  const handler = {} as typeof import("../../app/settings/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signout">> = Specific
  const handler = {} as typeof import("../../app/signout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/analytics">> = Specific
  const handler = {} as typeof import("../../app/systems/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/barcode/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/barcode">> = Specific
  const handler = {} as typeof import("../../app/systems/barcode/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/catalog">> = Specific
  const handler = {} as typeof import("../../app/systems/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/integrations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/integrations/new">> = Specific
  const handler = {} as typeof import("../../app/systems/integrations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/integrations">> = Specific
  const handler = {} as typeof import("../../app/systems/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/oms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/oms">> = Specific
  const handler = {} as typeof import("../../app/systems/oms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/orders">> = Specific
  const handler = {} as typeof import("../../app/systems/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems">> = Specific
  const handler = {} as typeof import("../../app/systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/pos">> = Specific
  const handler = {} as typeof import("../../app/systems/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/systems">> = Specific
  const handler = {} as typeof import("../../app/systems/systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/tms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/tms">> = Specific
  const handler = {} as typeof import("../../app/systems/tms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/wms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/wms">> = Specific
  const handler = {} as typeof import("../../app/systems/wms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/systems/wms/voice-picking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems/wms/voice-picking">> = Specific
  const handler = {} as typeof import("../../app/systems/wms/voice-picking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/agents">> = Specific
  const handler = {} as typeof import("../../app/api/ai/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/characters">> = Specific
  const handler = {} as typeof import("../../app/api/ai/characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/ai/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/invoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/invoke">> = Specific
  const handler = {} as typeof import("../../app/api/ai/invoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/train/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/train">> = Specific
  const handler = {} as typeof import("../../app/api/ai/train/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/targets/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/targets/upload">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/targets/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/post">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/catalog/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog/public">> = Specific
  const handler = {} as typeof import("../../app/api/catalog/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments">> = Specific
  const handler = {} as typeof import("../../app/api/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/flags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/flags">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/flags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/market/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/market/history">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/market/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/market/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/market/publish">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/market/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/nav/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/nav">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/nav/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/prefs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/prefs">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/prefs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/categories">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/items">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/locations">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations">> = Specific
  const handler = {} as typeof import("../../app/api/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/feed">> = Specific
  const handler = {} as typeof import("../../app/api/market/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market/feed/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/feed/stream">> = Specific
  const handler = {} as typeof import("../../app/api/market/feed/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/market/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market/posts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/market/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketplace/listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/listings">> = Specific
  const handler = {} as typeof import("../../app/api/marketplace/listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orgs/[orgId]/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orgs/[orgId]/settings">> = Specific
  const handler = {} as typeof import("../../app/api/orgs/[orgId]/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[id]/aggregate-rating/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/aggregate-rating">> = Specific
  const handler = {} as typeof import("../../app/api/products/[id]/aggregate-rating/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/[id]/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/products/[id]/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/me">> = Specific
  const handler = {} as typeof import("../../app/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/enterprise">> = Specific
  const handler = {} as typeof import("../../app/enterprise/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
