name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_BACKEND: ghcr.io/${{ github.repository }}-backend
      IMAGE_FRONTEND: ghcr.io/${{ github.repository }}-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Compute tags
        id: meta
        run: |
          SHA=$(git rev-parse --short=12 HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "build_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tregu_backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:sha-${{ steps.meta.outputs.sha }}
            ${{ env.IMAGE_BACKEND }}:latest
          build-args: |
            GIT_SHA=${{ steps.meta.outputs.sha }}
            BUILD_TIME=${{ steps.meta.outputs.build_time }}

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tregu_frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:sha-${{ steps.meta.outputs.sha }}
            ${{ env.IMAGE_FRONTEND }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://YOUR_DOMAIN/api
